server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Disable caching for JavaScript files to ensure updates are loaded
  location ~* \.js$ {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    add_header Pragma "no-cache";
    add_header Expires "0";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /web/ {
    try_files $uri =404;
  }
}