services:
  signaling:
    build: ./signaling
    network_mode: "host"

  game:
    build: ./game
    depends_on: [signaling]
    network_mode: "host"
    environment:
      - SIGNALING_URL=ws://localhost:9000
      - ROOM=room1
      - DISPLAY=${DISPLAY:-:0}
      - GAME_CMD=xterm -maximized -e /app/game_launcher.sh
      - GAME_NAME=
      - CAPTURE_MODE=${CAPTURE_MODE:-host}
    privileged: true
    devices:
      - /dev/uinput:/dev/uinput
    volumes:
      - ./games:/games:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro

  web:
    build: ./web
    depends_on: [signaling]
    network_mode: "host"