services:
  signaling:
    build: ./signaling
    network_mode: "host"

  game:
    build: ./game
    depends_on: [signaling]
    network_mode: "host"
    environment:
      - SIGNALING_URL=ws://localhost:9000
      - ROOM=room1
      - DISPLAY=:99
      - GAME_CMD=xterm -maximized -e /app/snake.sh
    privileged: true
    devices:
      - /dev/uinput:/dev/uinput

  web:
    build: ./web
    depends_on: [signaling]
    network_mode: "host"